### PR TITLE
Testing the build

### PR DESCRIPTION
**Pull request by bison**
Testing the build.

### CODE REVIEW

**Comment by bison** [comment]
Oops. Sorry.

**Comment by tonyg** [comment]
Wait, that looks interesting! I'm glad to see people working on it; should I expect some of these changes to be re-pull-requested in future?

**Comment by clarete** [comment]
@tonyg thanks a lot for the plugin in the first place. Such a simple and elegant solution for presence in the broker. We're gonna get 100% of test coverage on that guy and it will be awesome if these changes are useful for the project! We'll definitely re-open this PR when we have some more to show!! go :rabbit:!

**Comment by tonyg** [comment]
OK, thanks :-) I look forward to it!

**Comment by tonyg** [comment]
I'm doing a small amount of maintenance on the presence exchange today. If you'd like to see any patches land for a 3.5.x-compatible build of the presence exchange, now is a good time :-)

**Pull request closed without merging**
